#install.packages("caret")
library(caret)

d <- read.csv("data//train.csv", header=T)

str(d, list.len=ncol(d))

# define categorical variables
d$Product_Info_1      <-as.factor(d$Product_Info_1)
d$Product_Info_2      <-as.factor(d$Product_Info_2)
d$Product_Info_3      <-as.factor(d$Product_Info_3)
d$Product_Info_5      <-as.factor(d$Product_Info_5)
d$Product_Info_6      <-as.factor(d$Product_Info_6)
d$Product_Info_7      <-as.factor(d$Product_Info_7)
d$Employment_Info_2   <-as.factor(d$Employment_Info_2)
d$Employment_Info_3   <-as.factor(d$Employment_Info_3)
d$Employment_Info_5   <-as.factor(d$Employment_Info_5)
d$InsuredInfo_1       <-as.factor(d$InsuredInfo_1)
d$InsuredInfo_2       <-as.factor(d$InsuredInfo_2)
d$InsuredInfo_3       <-as.factor(d$InsuredInfo_3)
d$InsuredInfo_4       <-as.factor(d$InsuredInfo_4)
d$InsuredInfo_5       <-as.factor(d$InsuredInfo_5)
d$InsuredInfo_6       <-as.factor(d$InsuredInfo_6)
d$InsuredInfo_7       <-as.factor(d$InsuredInfo_7)
d$Insurance_History_1 <-as.factor(d$Insurance_History_1)
d$Insurance_History_2 <-as.factor(d$Insurance_History_2)
d$Insurance_History_3 <-as.factor(d$Insurance_History_3)
d$Insurance_History_4 <-as.factor(d$Insurance_History_4)
d$Insurance_History_7 <-as.factor(d$Insurance_History_7)
d$Insurance_History_8 <-as.factor(d$Insurance_History_8)
d$Insurance_History_9 <-as.factor(d$Insurance_History_9)
d$Family_Hist_1       <-as.factor(d$Family_Hist_1)
d$Medical_History_2   <-as.factor(d$Medical_History_2)
d$Medical_History_3   <-as.factor(d$Medical_History_3)
d$Medical_History_4   <-as.factor(d$Medical_History_4)
d$Medical_History_5   <-as.factor(d$Medical_History_5)
d$Medical_History_6   <-as.factor(d$Medical_History_6)
d$Medical_History_7   <-as.factor(d$Medical_History_7)
d$Medical_History_8   <-as.factor(d$Medical_History_8)
d$Medical_History_9   <-as.factor(d$Medical_History_9)
d$Medical_History_10  <-as.factor(d$Medical_History_10)
d$Medical_History_11  <-as.factor(d$Medical_History_11)
d$Medical_History_12  <-as.factor(d$Medical_History_12)
d$Medical_History_13  <-as.factor(d$Medical_History_13)
d$Medical_History_14  <-as.factor(d$Medical_History_14)
d$Medical_History_16  <-as.factor(d$Medical_History_16)
d$Medical_History_17  <-as.factor(d$Medical_History_17)
d$Medical_History_18  <-as.factor(d$Medical_History_18)
d$Medical_History_19  <-as.factor(d$Medical_History_19)
d$Medical_History_20  <-as.factor(d$Medical_History_20)
d$Medical_History_21  <-as.factor(d$Medical_History_21)
d$Medical_History_22  <-as.factor(d$Medical_History_22)
d$Medical_History_23  <-as.factor(d$Medical_History_23)
d$Medical_History_25  <-as.factor(d$Medical_History_25)
d$Medical_History_26  <-as.factor(d$Medical_History_26)
d$Medical_History_27  <-as.factor(d$Medical_History_27)
d$Medical_History_28  <-as.factor(d$Medical_History_28)
d$Medical_History_29  <-as.factor(d$Medical_History_29)
d$Medical_History_30  <-as.factor(d$Medical_History_30)
d$Medical_History_31  <-as.factor(d$Medical_History_31)
d$Medical_History_33  <-as.factor(d$Medical_History_33)
d$Medical_History_34  <-as.factor(d$Medical_History_34)
d$Medical_History_35  <-as.factor(d$Medical_History_35)
d$Medical_History_36  <-as.factor(d$Medical_History_36)
d$Medical_History_37  <-as.factor(d$Medical_History_37)
d$Medical_History_38  <-as.factor(d$Medical_History_38)
d$Medical_History_39  <-as.factor(d$Medical_History_39)
d$Medical_History_40  <-as.factor(d$Medical_History_40)
d$Medical_History_41  <-as.factor(d$Medical_History_41)


# convert categorical variables to dummy
d.tmp <- dummyVars(~., data=d)
d.dummy <- as.data.frame(predict(d.tmp, d))

str(d, list.len=ncol(d.dummy))







