#install.packages("caret")
library(caret)

train <- read.csv("data//train.csv", header=T)
str(train, list.len=ncol(train))

# define categorical variables
train$Product_Info_1      <-as.factor(train$Product_Info_1)
train$Product_Info_2      <-as.factor(train$Product_Info_2)
train$Product_Info_3      <-as.factor(train$Product_Info_3)
train$Product_Info_5      <-as.factor(train$Product_Info_5)
train$Product_Info_6      <-as.factor(train$Product_Info_6)
train$Product_Info_7      <-as.factor(train$Product_Info_7)
train$Employment_Info_2   <-as.factor(train$Employment_Info_2)
train$Employment_Info_3   <-as.factor(train$Employment_Info_3)
train$Employment_Info_5   <-as.factor(train$Employment_Info_5)
train$InsuredInfo_1       <-as.factor(train$InsuredInfo_1)
train$InsuredInfo_2       <-as.factor(train$InsuredInfo_2)
train$InsuredInfo_3       <-as.factor(train$InsuredInfo_3)
train$InsuredInfo_4       <-as.factor(train$InsuredInfo_4)
train$InsuredInfo_5       <-as.factor(train$InsuredInfo_5)
train$InsuredInfo_6       <-as.factor(train$InsuredInfo_6)
train$InsuredInfo_7       <-as.factor(train$InsuredInfo_7)
train$Insurance_History_1 <-as.factor(train$Insurance_History_1)
train$Insurance_History_2 <-as.factor(train$Insurance_History_2)
train$Insurance_History_3 <-as.factor(train$Insurance_History_3)
train$Insurance_History_4 <-as.factor(train$Insurance_History_4)
train$Insurance_History_7 <-as.factor(train$Insurance_History_7)
train$Insurance_History_8 <-as.factor(train$Insurance_History_8)
train$Insurance_History_9 <-as.factor(train$Insurance_History_9)
train$Family_Hist_1       <-as.factor(train$Family_Hist_1)
train$Medical_History_2   <-as.factor(train$Medical_History_2)
train$Medical_History_3   <-as.factor(train$Medical_History_3)
train$Medical_History_4   <-as.factor(train$Medical_History_4)
train$Medical_History_5   <-as.factor(train$Medical_History_5)
train$Medical_History_6   <-as.factor(train$Medical_History_6)
train$Medical_History_7   <-as.factor(train$Medical_History_7)
train$Medical_History_8   <-as.factor(train$Medical_History_8)
train$Medical_History_9   <-as.factor(train$Medical_History_9)
train$Medical_History_10  <-as.factor(train$Medical_History_10)
train$Medical_History_11  <-as.factor(train$Medical_History_11)
train$Medical_History_12  <-as.factor(train$Medical_History_12)
train$Medical_History_13  <-as.factor(train$Medical_History_13)
train$Medical_History_14  <-as.factor(train$Medical_History_14)
train$Medical_History_16  <-as.factor(train$Medical_History_16)
train$Medical_History_17  <-as.factor(train$Medical_History_17)
train$Medical_History_18  <-as.factor(train$Medical_History_18)
train$Medical_History_19  <-as.factor(train$Medical_History_19)
train$Medical_History_20  <-as.factor(train$Medical_History_20)
train$Medical_History_21  <-as.factor(train$Medical_History_21)
train$Medical_History_22  <-as.factor(train$Medical_History_22)
train$Medical_History_23  <-as.factor(train$Medical_History_23)
train$Medical_History_25  <-as.factor(train$Medical_History_25)
train$Medical_History_26  <-as.factor(train$Medical_History_26)
train$Medical_History_27  <-as.factor(train$Medical_History_27)
train$Medical_History_28  <-as.factor(train$Medical_History_28)
train$Medical_History_29  <-as.factor(train$Medical_History_29)
train$Medical_History_30  <-as.factor(train$Medical_History_30)
train$Medical_History_31  <-as.factor(train$Medical_History_31)
train$Medical_History_33  <-as.factor(train$Medical_History_33)
train$Medical_History_34  <-as.factor(train$Medical_History_34)
train$Medical_History_35  <-as.factor(train$Medical_History_35)
train$Medical_History_36  <-as.factor(train$Medical_History_36)
train$Medical_History_37  <-as.factor(train$Medical_History_37)
train$Medical_History_38  <-as.factor(train$Medical_History_38)
train$Medical_History_39  <-as.factor(train$Medical_History_39)
train$Medical_History_40  <-as.factor(train$Medical_History_40)
train$Medical_History_41  <-as.factor(train$Medical_History_41)


# convert categorical variables to dummy
train.tmp <- dummyVars(~., data=train)
train.dummy <- as.data.frame(predict(train.tmp, train))

str(train, list.len=ncol(train.dummy))






