!obj:pylearn2.train.Train {
    dataset: &train !pkl: "lab/suuji_dake.csv",
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 5,
        layers: [
                 !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h1',
                     layer_content: !pkl: "DAE_l1.pkl"
                 },
                 !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h2',
                     layer_content: !pkl: "DAE_l2.pkl"
                 },
                 !obj:pylearn2.models.mlp.LinearGaussian {
                    #ーーわからんーーーーーーーーーーーーーーーーーーーーーーーー
                     init_bias: !obj:pylearn2.models.mlp.mean_of_targets { 
                       dataset: *train },
                     init_beta: !obj:pylearn2.models.mlp.beta_from_targets { 
                       dataset: *train },
                     min_beta: 1.,
                     max_beta: 100.,
                     beta_lr_scale: 1.,
                     dim: 1,
                     # max_col_norm: 1.9365,
                     layer_name: 'y',
                     irange: .005
                    #ーーわからんーーーーーーーーーーーーーーーーーーーーーーーー
                 }
                ],
        nvis: 200
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        #わからん
    },
    extensions: [
        #わからん
    ],
    save_path: "mlp.pkl",
    save_freq: 1
}